name: image-build
on:
  push:
    branches:
      - "master"
    tags:
      - "*"
jobs:
  image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo.
        uses: actions/checkout@v3

      - name: build and push docker image.
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          image: liy36/metrics
          tags: latest
          dockerfile: ci/Dockerfile
          username: ${{ secrets.REGISTRY_LOGIN }}
          password: ${{ secrets.REGISTRY_TOKEN }}
