name: image-build
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
jobs:
  image-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo.
        uses: actions/checkout@v2

      - name: build and push docker image.
        uses: sckirg/build-and-push-action@v2
        with: 
          registry: registry.cn-hangzhou.aliyuncs.com
          registry_namespace: liy36
          registry_username: ${{ secrets.REGISTRY_LOGIN }}
          registry_token: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: "ci/Diockerfile"
          image_name: metrics
          tag: ${GITHUB_REF#refs/*/}
